package DAMSApp;


/**
* DAMSApp/DAMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/DAMS.idl
* Sunday, March 27, 2022 8:15:00 PM EDT
*/

public interface DAMS extends DAMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DAMS
