package DAMSApp;

/**
* DAMSApp/DAMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/DAMS.idl
* Sunday, March 27, 2022 8:15:00 PM EDT
*/

public final class DAMSHolder implements org.omg.CORBA.portable.Streamable
{
  public DAMSApp.DAMS value = null;

  public DAMSHolder ()
  {
  }

  public DAMSHolder (DAMSApp.DAMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DAMSApp.DAMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DAMSApp.DAMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DAMSApp.DAMSHelper.type ();
  }

}
