package DAMSApp;


/**
* DAMSApp/DAMSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/DAMS.idl
* Saturday, March 26, 2022 2:01:47 PM EDT
*/

public abstract class DAMSPOA extends org.omg.PortableServer.Servant
 implements DAMSApp.DAMSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addAppointment", new java.lang.Integer (0));
    _methods.put ("removeAppointment", new java.lang.Integer (1));
    _methods.put ("listAppointmentAvailability", new java.lang.Integer (2));
    _methods.put ("bookAppointment", new java.lang.Integer (3));
    _methods.put ("getAppointmentSchedule", new java.lang.Integer (4));
    _methods.put ("cancelAppointment", new java.lang.Integer (5));
    _methods.put ("swapAppointment", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DAMSApp/DAMS/addAppointment
       {
         String appointmentID = in.read_string ();
         String appoinmentType = in.read_string ();
         String capacity = in.read_string ();
         String $result = null;
         $result = this.addAppointment (appointmentID, appoinmentType, capacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DAMSApp/DAMS/removeAppointment
       {
         String appointmentID = in.read_string ();
         String appoinmentType = in.read_string ();
         String $result = null;
         $result = this.removeAppointment (appointmentID, appoinmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DAMSApp/DAMS/listAppointmentAvailability
       {
         String appoinmentType = in.read_string ();
         String $result = null;
         $result = this.listAppointmentAvailability (appoinmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DAMSApp/DAMS/bookAppointment
       {
         String patientID = in.read_string ();
         String appoinmentID = in.read_string ();
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.bookAppointment (patientID, appoinmentID, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DAMSApp/DAMS/getAppointmentSchedule
       {
         String patientID = in.read_string ();
         String $result = null;
         $result = this.getAppointmentSchedule (patientID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DAMSApp/DAMS/cancelAppointment
       {
         String patientID = in.read_string ();
         String appoinmentID = in.read_string ();
         String $result = null;
         $result = this.cancelAppointment (patientID, appoinmentID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DAMSApp/DAMS/swapAppointment
       {
         String patientID = in.read_string ();
         String oldAppointmentID = in.read_string ();
         String oldAppoinmentType = in.read_string ();
         String newAppointmentID = in.read_string ();
         String newAppoinmentType = in.read_string ();
         String $result = null;
         $result = this.swapAppointment (patientID, oldAppointmentID, oldAppoinmentType, newAppointmentID, newAppoinmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DAMSApp/DAMS/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DAMSApp/DAMS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DAMS _this() 
  {
    return DAMSHelper.narrow(
    super._this_object());
  }

  public DAMS _this(org.omg.CORBA.ORB orb) 
  {
    return DAMSHelper.narrow(
    super._this_object(orb));
  }


} // class DAMSPOA
