package DAMSApp;


/**
* DAMSApp/DAMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/DAMS.idl
* Saturday, April 2, 2022 1:26:42 PM EDT
*/

public interface DAMS extends DAMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DAMS
