package DAMSApp;


/**
* DAMSApp/DAMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/DAMS.idl
* Saturday, March 26, 2022 2:01:47 PM EDT
*/

public interface DAMS extends DAMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DAMS
