package DAMSApp;


/**
* DAMSApp/DAMSHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/DAMS.idl
* Saturday, March 26, 2022 2:01:47 PM EDT
*/

abstract public class DAMSHelper
{
  private static String  _id = "IDL:DAMSApp/DAMS:1.0";

  public static void insert (org.omg.CORBA.Any a, DAMSApp.DAMS that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DAMSApp.DAMS extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DAMSApp.DAMSHelper.id (), "DAMS");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DAMSApp.DAMS read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DAMSStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DAMSApp.DAMS value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DAMSApp.DAMS narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DAMSApp.DAMS)
      return (DAMSApp.DAMS)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DAMSApp._DAMSStub stub = new DAMSApp._DAMSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DAMSApp.DAMS unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DAMSApp.DAMS)
      return (DAMSApp.DAMS)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DAMSApp._DAMSStub stub = new DAMSApp._DAMSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
