package DAMSApp;


/**
* DAMSApp/DAMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/DAMS.idl
* Sunday, March 27, 2022 8:15:00 PM EDT
*/

public interface DAMSOperations 
{
  String addAppointment (String appointmentID, String appoinmentType, String capacity);
  String removeAppointment (String appointmentID, String appoinmentType);
  String listAppointmentAvailability (String appoinmentType);
  String bookAppointment (String patientID, String appoinmentID, String appointmentType);
  String getAppointmentSchedule (String patientID);
  String cancelAppointment (String patientID, String appoinmentID);
  String swapAppointment (String patientID, String oldAppointmentID, String oldAppoinmentType, String newAppointmentID, String newAppoinmentType);
  void shutdown ();
} // interface DAMSOperations
